{{- if and (.Values.postgresql.enabled) (.Values.postgresql.persistence.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: {{ .Values.postgresql.persistence.storageClassName | default "default" }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | default "20Gi" }}
{{- end }}