apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertflow.fullname" . }}
  labels:
    {{- include "alertflow.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.alertflow.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "alertflow.alertflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "alertflow.alertflow.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alertflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.postgresql.enabled }}
      initContainers:
        - name: wait-for
          image: ghcr.io/patrickdappollonio/wait-for:latest
          env:
          - name: POSTGRES_HOST
            value: "alertflow-postgresql:5432"
          command:
            - /wait-for
          args:
            - --host="$(POSTGRES_HOST)"
            - --verbose
      {{- end }}
      containers:
        - name: alertflow
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.alertflow.repository }}:{{ .Values.alertflow.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.alertflow.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.alertflow.service.ports.backend.port }}
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.alertflow.service.ports.backend.port }}
          {{- if .Values.alertflow.configMap.enabled }}
          volumeMounts:
            - name: backend-config
              mountPath: /etc/alertflow/backend_config.yaml
              subPath: backend_config.yaml
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.alertflow.configMap.enabled }}
      volumes:
        - name: backend-config
          configMap:
            name: {{ include "alertflow.fullname" . }}-config
            items:
              - key: config.yaml
                path: backend_config.yaml
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
