apiVersion: v2
name: alertflow
description: An AlertFlow Helm chart for Kubernetes
type: application
version: 1.4.5
appVersion: "v1.4.0"

# add postgresdb
dependencies:
  - name: postgresql
    version: 16.5.0
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    tags:
      - database
