apiVersion: v2
name: exflow
description: An exFlow Helm chart for Kubernetes
type: application
version: 1.8.3
appVersion: "v1.3.1"

# add postgresdb
dependencies:
  - name: postgresql
    version: 16.7.4
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    tags:
      - database
