# Default values for exflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# My Custom Space

exflow:
  replicas: 1
  repository: justnz/exflow
  pullPolicy: Always
  tag: ""
  configMap:
    enabled: true
    data:
      LogLevel: info
      Port: 8080
      Database:
        Server: exflow-postgresql
        Port: 5432
        Name: exflow
        User: exflow
        Password: exflow
      Encryption:
        Enabled: true
        Key: key
      JWT:
        Secret: secret
  service:
    name: exflow
    type: ClusterIP
    ports:
      frontend:
        port: 3000
        targetPort: 3000
        name: frontend
      backend:
        port: 8080
        targetPort: 8080
        name: backend

postgresql:
  enabled: true
  volumePermissions:
    enabled: true
  primary:
    persistence:
      accessModes:
        - ReadWriteMany
      size: 20Gi
  global:
    postgresql:
      auth:
        database: "exflow"
        password: "exflow"
        username: "exflow"

projectRunner:
  enabled: false
  replicas: 2
  repository: justnz/runner
  pullPolicy: Always
  tag: "v1.0.4"
  persistence:
    enabled: false
    accessMode: ReadWriteMany
    size: 5Gi
  configMap:
    enabled: true
    data:
      log_level: info
      mode: master
      alertflow:
        enabled: false
      exflow:
        url: http://localhost:8080
        api_key: 1234567890
      plugins:
        - name: git
          version: v1.0.1
        - name: ansible
          version: v1.0.1
        - name: ssh
          version: v1.1.3
      alert_endpoints:
        port: 8080
  service:
    name: project-runner
    type: ClusterIP
    port: 8080
    target_port: 8080

sharedRunner:
  enabled: false
  replicas: 2
  repository: justnz/runner
  pullPolicy: Always
  tag: "v1.0.4"
  persistence:
    enabled: false
    accessMode: ReadWriteMany
    size: 5Gi
  configMap:
    enabled: true
    data:
      log_level: info
      mode: master
      alertflow:
        enabled: false
      exflow:
        url: http://localhost:8080
        api_key: 1234567890
      plugins:
        - name: git
          version: v1.0.1
        - name: ansible
          version: v1.0.1
        - name: ssh
          version: v1.1.3
      alert_endpoints:
        port: 8080
  service:
    name: shared-runner
    type: ClusterIP
    port: 8080
    target_port: 8080

# My Custom Space end

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - exflow.org
    - www.exflow.org
  tls:
    - secretName: exflow-org-tls
      hosts:
        - exflow.org
        - www.exflow.org

resources:
  requests: {}

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
