name: Generate Helm Chart README

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate README.md using helm-docs GitHub Action
      - name: Generate README.md
        uses: losisin/helm-docs-github-action@v1
        with:
          chart-search-root: charts/

      # Step 3: Commit and push the updated README.md
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add charts/**/README.md
          git commit -m "Update README.md with helm-docs" || echo "No changes to commit"
          git push origin main
