name: Generate Helm Chart README

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate README.md using helm-docs GitHub Action
      - name: Generate README.md
        uses: losisin/helm-docs-github-action@v1
        with:
          git-push: true
