name: Publish Helm Charts

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    paths:
      - 'charts/**'  # Only trigger if files in the charts/ directory are modified
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
    paths:
      - 'charts/**'  # Only trigger if files in the charts/ directory are modified

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Update Helm dependencies
        run: |
          for chart in $(ls -d charts/*/); do
            if [ -f "$chart/Chart.yaml" ]; then
              helm dependency update $chart
            fi
          done

       # Package all charts in the charts/ directory
      - name: Package Helm charts
        run: |
          mkdir -p packaged
          for chart in $(ls -d charts/*/); do
            if [ -f "$chart/Chart.yaml" ]; then
              helm package $chart -d packaged
            else
              echo "Skipping $chart: Chart.yaml file is missing"
            fi
          done

      # Create or update index.yaml
      - name: Update Helm repository index
        run: |
          if git ls-remote --exit-code origin gh-pages; then
            git fetch origin gh-pages
            git checkout gh-pages -- index.yaml || echo "No existing index.yaml found"
          fi
          helm repo index packaged --url https://v1flows.github.io/helm-charts --merge index.yaml
          mv packaged/* .

      # Commit and push to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
